(() => {
  const browserDefaultApi = ["localhost", "127.0.0.1"].includes(window.location.hostname) && window.location.port !== "8000"
    ? "http://127.0.0.1:8000"
    : window.location.origin;
  const API = (window.SETU_API_URL || localStorage.getItem("setu_api_url") || browserDefaultApi).replace(/\/$/, "");
  const app = document.querySelector("#app");
  const demoUser = "student", demoPassword = "setu123";
  const esc = (value) => String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;" }[c]));
  const today = new Date().toISOString().slice(0, 10);
  let selectedTrain = "12123";
  let telemetryTimer = null;
  const savedTheme = localStorage.getItem("setu_theme") || "light";
  document.documentElement.dataset.theme = savedTheme;
  const get = async (path, options) => {
    const response = await fetch(`${API}${path}`, options);
    const data = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(data.detail || `Request failed (${response.status})`);
    return data;
  };
  const toast = (message) => { const node = document.createElement("div"); node.className = "toast"; node.textContent = message; document.body.append(node); setTimeout(() => node.remove(), 3200); };
  const loggedIn = () => sessionStorage.getItem("setu_logged_in") === "yes";

  function renderLogin() {
    app.innerHTML = `<section class="login"><form class="login-card" id="loginForm">
      <div class="brand"><span class="brand-mark">↗</span> SETU</div>
      <div class="eyebrow">Train intelligence made simple</div><h1>Welcome aboard.</h1>
      <p>See trains, delays, weather, routes and helpful predictions in one friendly place.</p>
      <div class="field"><label for="username">Username</label><input id="username" autocomplete="username" placeholder="Enter username" required></div>
      <div class="field"><label for="password">Password</label><input id="password" type="password" autocomplete="current-password" placeholder="Enter password" required></div>
      <div class="error" id="loginError"></div><button class="primary">Log in</button>
      <div class="demo">Demo login: <b>student</b> / <b>setu123</b></div>
    </form></section>`;
    document.querySelector("#loginForm").addEventListener("submit", (event) => {
      event.preventDefault();
      const user = document.querySelector("#username").value.trim(), pass = document.querySelector("#password").value;
      if (user === demoUser && pass === demoPassword) { sessionStorage.setItem("setu_logged_in", "yes"); renderDashboard(); }
      else document.querySelector("#loginError").textContent = "That username or password is not correct.";
    });
  }

  function renderDashboard() {
    app.innerHTML = `<div class="shell"><header class="topbar"><div class="brand"><span class="brand-mark">↗</span> SETU</div><div class="top-actions"><button class="soft" id="themeToggle" aria-label="Switch theme">${document.documentElement.dataset.theme === "dark" ? "☀️ Light" : "🌙 Dark"}</button><span class="muted">Hello, student</span><span class="user-dot">S</span><button class="soft" id="logout">Log out</button></div></header>
      <div class="layout"><nav class="side"><button class="active" data-page="overview">Overview</button><button data-page="train">Track a train</button><button data-page="fleet">Fleet radar</button><button data-page="station">Station board</button><button data-page="tools">Smart tools</button><button data-page="feedback">Feedback</button></nav><section class="content" id="view"></section></div></div>`;
    document.querySelector("#themeToggle").onclick = () => {
      const nextTheme = document.documentElement.dataset.theme === "dark" ? "light" : "dark";
      document.documentElement.dataset.theme = nextTheme;
      localStorage.setItem("setu_theme", nextTheme);
      document.querySelector("#themeToggle").textContent = nextTheme === "dark" ? "☀️ Light" : "🌙 Dark";
    };
    document.querySelector("#logout").onclick = () => { sessionStorage.removeItem("setu_logged_in"); renderLogin(); };
    document.querySelectorAll("[data-page]").forEach((button) => button.onclick = () => { if (telemetryTimer) { clearInterval(telemetryTimer); telemetryTimer = null; } document.querySelectorAll("[data-page]").forEach((b) => b.classList.remove("active")); button.classList.add("active"); pages[button.dataset.page](); });
    pages.overview();
  }

  const shell = (title, subtitle, body) => `<div class="hero"><div><div class="eyebrow">SETU control room</div><h1>${title}</h1><p>${subtitle}</p></div><div class="status"><i class="pulse"></i> System ready</div></div>${body}`;
  const view = () => document.querySelector("#view");
  const loading = () => { view().innerHTML = `<div class="card full"><p class="muted">Loading your train information…</p></div>`; };

  const pages = {
    overview: async () => { loading(); try { const [forecast, fleet] = await Promise.all([get(`/api/v1/trains/12123/forecast?date=${today}`), get("/api/v1/corridor/fleet-overview")]); view().innerHTML = shell("Good evening, student.", "Here is the most important railway information, explained simply.", `<div class="search-row"><input id="quickTrain" value="${esc(selectedTrain)}" placeholder="Train number, for example 12123"><button class="primary" id="quickSearch">Check train</button></div><div class="grid">${forecastCard(forecast)}<div class="card"><h2>Fleet radar</h2><div class="metric">${fleet.active_monitored_rakes}</div><div class="muted">trains being watched</div><div class="progress"><i style="width:${Math.min(100, fleet.active_monitored_rakes * 20)}%"></i></div><button class="soft" data-jump="fleet">See all trains →</button></div><div class="card"><h2>What SETU does</h2><div class="list"><div class="list-item"><span>Predict</span><span class="muted">future delay</span></div><div class="list-item"><span>Explain</span><span class="muted">why it happens</span></div><div class="list-item"><span>Connect</span><span class="muted">live railway data</span></div></div></div><div class="card wide"><h2>Fleet at a glance</h2>${fleetTable(fleet.fleet)}</div></div>`); document.querySelector("#quickSearch").onclick = () => { selectedTrain = document.querySelector("#quickTrain").value.trim() || "12123"; pages.train(); }; document.querySelector("[data-jump]").onclick = () => pages.fleet(); } catch (e) { showError(e); } },
    train: () => { view().innerHTML = shell("Track a train.", "Type a train number and SETU will explain its journey.", `<div class="search-row"><input id="trainNumber" value="${esc(selectedTrain)}" placeholder="Example: 12123"><input id="journeyDate" type="date" value="${today}"><button class="primary" id="searchTrain">Find train</button></div><div id="trainResult"></div>`); document.querySelector("#searchTrain").onclick = () => { selectedTrain = document.querySelector("#trainNumber").value.trim() || "12123"; loadTrain(selectedTrain, document.querySelector("#journeyDate").value); }; loadTrain(selectedTrain, today); },
    fleet: async () => { loading(); try { const data = await get("/api/v1/corridor/fleet-overview"); view().innerHTML = shell("Fleet radar.", "A simple view of all trains SETU is watching right now.", `<div class="card full"><h2>${esc(data.corridor_name)}</h2>${fleetTable(data.fleet)}</div>`); } catch (e) { showError(e); } },
    station: () => { view().innerHTML = shell("Station board.", "See trains arriving at a station in the next few hours.", `<div class="search-row"><input id="stationCode" value="KYN" placeholder="Station code, for example KYN"><button class="primary" id="searchStation">Show board</button></div><div id="stationResult"></div>`); document.querySelector("#searchStation").onclick = () => loadStation(document.querySelector("#stationCode").value); loadStation("KYN"); },
    tools: () => { view().innerHTML = shell("Smart tools.", "Helpful tools for people who run and plan railway journeys.", `<div class="grid"><div class="card wide"><h2>Dispatch solver</h2><p class="muted">Choose two trains to get a simple suggested action.</p><div class="search-row"><input id="trainA" value="12123" placeholder="Train A"><input id="trainB" value="22436" placeholder="Train B"><button class="primary" id="solve">Solve</button></div><div id="solveResult"></div></div><div class="card"><h2>Live telemetry</h2><p class="muted">Watch a train move. SETU refreshes every 3 seconds.</p><div class="search-row"><input id="telemetryTrain" value="${esc(selectedTrain)}"><button class="soft" id="telemetry">Start monitor</button></div><div id="telemetryResult"></div></div><div class="card full"><h2>Route intelligence map</h2><p class="muted">A quick visual of the train's corridor and planned stops.</p><div id="routeResult"><button class="soft" id="route">Load route map</button></div></div></div>`); document.querySelector("#solve").onclick = loadSolve; document.querySelector("#telemetry").onclick = () => { loadTelemetry(); if (telemetryTimer) clearInterval(telemetryTimer); telemetryTimer = setInterval(loadTelemetry, 3000); }; document.querySelector("#route").onclick = loadRoute; },
    feedback: () => { view().innerHTML = shell("Tell us what you think.", "Your message helps make train journeys better for everyone.", `<div class="card wide"><form id="feedbackForm"><div class="field"><label>Feedback type</label><select id="feedbackType"><option>General Feedback</option><option>Bug Report</option><option>Feature Request</option><option>Journey Experience</option></select></div><div class="field"><label>Rating (1–5)</label><input id="rating" type="number" min="1" max="5" value="5"></div><div class="field"><label>Your message</label><textarea id="message" rows="5" minlength="3" required placeholder="Tell us what happened…"></textarea></div><div class="field"><label>Your email (optional)</label><input id="email" type="email" placeholder="you@example.com"></div><button class="primary">Send feedback</button></form></div>`); document.querySelector("#feedbackForm").onsubmit = submitFeedback; }
  };

  function forecastCard(data) { const confidence = Math.round(data.confidence_score || 0); const source = data.data_is_live ? "Live provider data" : "Estimated demo data — add RAPIDAPI_KEY for live status"; return `<div class="card wide"><h2>${esc(data.train_name)} <span class="badge">${esc(data.train_number)}</span></h2><p class="muted">Journey date: <b>${esc(data.journey_date)}</b> · Checked: <b>${data.observed_at ? new Date(data.observed_at).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" }) : "—"}</b></p><div class="train-summary"><div class="summary-box"><span class="muted">Status</span><strong>${esc(data.current_status)}</strong></div><div class="summary-box"><span class="muted">Now delayed</span><strong>${data.current_delay_mins}m</strong></div><div class="summary-box"><span class="muted">Predicted</span><strong>${data.predicted_downstream_delay_mins}m</strong></div><div class="summary-box"><span class="muted">Confidence</span><strong>${confidence}%</strong></div></div><div class="progress"><i style="width:${confidence}%"></i></div><div class="notice"><b>Next station: ${esc(data.next_station)}</b>. Weather: ${esc(data.weather_telemetry?.condition)} (${data.weather_telemetry?.visibility_meters ?? "—"}m visibility).<br><small>${esc(source)}</small></div></div>`; }
  function fleetTable(items = []) { return `<div class="table-wrap"><table class="table"><thead><tr><th>Train</th><th>Station</th><th>Delay</th><th>Risk</th></tr></thead><tbody>${items.map((item) => `<tr><td><b>${esc(item.train_number)}</b><br><span class="muted">${esc(item.train_name)}</span></td><td>${esc(item.current_station)}</td><td>${item.current_delay_mins}m</td><td><span class="badge ${item.operational_risk.includes("CRITICAL") ? "danger" : item.operational_risk.includes("MODERATE") ? "warn" : ""}">${esc(item.operational_risk)}</span></td></tr>`).join("")}</tbody></table></div>`; }
  async function loadTrain(number, date = today) { const result = document.querySelector("#trainResult"); if (!result) return; result.innerHTML = `<div class="card full"><p class="muted">Checking train ${esc(number)}…</p></div>`; try { const data = await get(`/api/v1/trains/${encodeURIComponent(number.trim())}/forecast?date=${encodeURIComponent(date)}`); const risk = Math.min(100, Math.round((data.current_delay_mins * 1.5) + (100 - (data.confidence_score || 0)))); result.innerHTML = `<div class="grid">${forecastCard(data)}<div class="card"><h2>Delay reasons</h2><div class="list">${(data.root_causes || []).map((reason) => `<div class="list-item"><span>${esc(reason.factor)}</span><b>+${reason.impact_mins}m</b></div>`).join("") || `<span class="muted">No major delay reason found.</span>`}</div></div><div class="card"><h2>Prediction range</h2><div class="metric">${data.prediction_interval.p10_mins}–${data.prediction_interval.p90_mins}m</div><p class="muted">SETU's likely delay window.</p></div><div class="card"><h2>Journey risk score</h2><div class="metric">${risk}/100</div><div class="progress"><i style="width:${risk}%;background:${risk > 65 ? "linear-gradient(90deg,#e59a26,#e05252)" : "linear-gradient(90deg,#19a974,#58c98f)"}"></i></div><p class="muted">${risk > 65 ? "Keep extra time ready." : "Journey looks manageable."}</p></div><div class="card full"><h2>Journey steps</h2><div class="list">${(data.timeline || []).map((stop) => `<div class="list-item"><span><b>${esc(stop.station)}</b><br><span class="muted">${esc(stop.status)}</span></span><span>${esc(stop.predicted)}</span></div>`).join("")}</div><div class="form-actions"><button class="soft" id="explainTrain">Explain this simply</button><button class="soft" id="downloadReport">Download report</button></div><div id="aiExplanation" class="notice hidden"></div></div></div>`; document.querySelector("#explainTrain").onclick = async () => { const box = document.querySelector("#aiExplanation"); box.classList.remove("hidden"); box.textContent = "AI is explaining the verified train facts…"; try { const explanation = await get(`/api/v1/trains/${encodeURIComponent(data.train_number)}/explanation`, { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ forecast:data }) }); box.textContent = `${explanation.explanation} (${explanation.source})`; } catch (error) { box.textContent = error.message; } }; document.querySelector("#downloadReport").onclick = () => downloadReport(data, risk); } catch (e) { result.innerHTML = `<div class="card full"><p class="error">${esc(e.message)}</p></div>`; } }
  function downloadReport(data, risk) { const report = `SETU TRAIN REPORT\n\nTrain: ${data.train_number} - ${data.train_name}\nJourney date: ${data.journey_date}\nChecked: ${data.observed_at}\nStatus: ${data.current_status}\nNext station: ${data.next_station}\nCurrent delay: ${data.current_delay_mins} minutes\nPredicted delay: ${data.predicted_downstream_delay_mins} minutes\nConfidence: ${data.confidence_score}%\nJourney risk: ${risk}/100\nData source: ${data.telemetry_source}\n`; const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([report], { type:"text/plain" })); link.download = `setu-${data.train_number}-report.txt`; link.click(); URL.revokeObjectURL(link.href); toast("Report downloaded."); }
  async function loadStation(code) { const result = document.querySelector("#stationResult"); if (!result) return; result.innerHTML = `<div class="card full"><p class="muted">Reading station board…</p></div>`; try { const data = await get(`/api/v1/stations/${encodeURIComponent(code.trim())}/board`), board = data.board?.data || []; result.innerHTML = `<div class="card full"><h2>Station ${esc(data.station_code)} <span class="badge">${data.queried_time_window_hours} hour window</span></h2><div class="list">${board.map((train) => `<div class="list-item"><span><b>${esc(train.train_number)} · ${esc(train.train_name)}</b><br><span class="muted">${esc(train.scheduled_arrival)} → ${esc(train.actual_arrival)}</span></span><span class="badge warn">${esc(train.delay)}</span></div>`).join("") || `<span class="muted">No trains found.</span>`}</div></div>`; } catch (e) { result.innerHTML = `<div class="card full"><p class="error">${esc(e.message)}</p></div>`; } }
  async function loadTelemetry() { const result = document.querySelector("#telemetryResult"); if (!result) return; try { const data = await get(`/api/v1/trains/${encodeURIComponent(document.querySelector("#telemetryTrain").value.trim())}/telemetry`), t = data.live_telemetry; result.innerHTML = `<div class="notice"><b>${esc(t.active_block_section)}</b><br><strong>${t.current_speed_kmh} km/h</strong> · ${t.section_progress_pct}% through section<br><small>${t.latitude}, ${t.longitude} · Updated ${new Date().toLocaleTimeString()}</small></div>`; } catch (e) { result.innerHTML = `<p class="error">${esc(e.message)}</p>`; } }
  async function loadRoute() { const result = document.querySelector("#routeResult"); try { const number = document.querySelector("#telemetryTrain").value.trim() || selectedTrain, data = await get(`/api/v1/trains/${encodeURIComponent(number)}/route-geometry`), points = data.critical_waypoints || []; const labels = points.map((point, index) => `<span class="map-label" style="left:${8 + (index * 84 / Math.max(1, points.length - 1))}%;top:${35 + ((index % 2) * 26)}%">${esc(point.code)}</span>`).join(""); result.innerHTML = `<div class="map">${labels}</div><div class="list">${(data.stations || []).slice(0, 6).map((station) => `<div class="list-item"><span><b>${esc(station.station_name)}</b><br><span class="muted">${esc(station.status)}</span></span><span>${esc(station.scheduled_arrival)}</span></div>`).join("")}</div>`; } catch (e) { result.innerHTML = `<p class="error">${esc(e.message)}</p>`; } }
  async function loadSolve() { const result = document.querySelector("#solveResult"); try { const a = document.querySelector("#trainA").value.trim(), b = document.querySelector("#trainB").value.trim(), data = await get(`/api/v1/authority/dispatch-solve?train_a=${encodeURIComponent(a)}&train_b=${encodeURIComponent(b)}`, { method:"POST" }); result.innerHTML = `<div class="notice"><b>${esc(data.optimal_action)}</b><br>${esc(data.rationale)}<br><br>Could save <b>${data.projected_systemic_delay_saved_mins} minutes</b>.</div>`; } catch (e) { result.innerHTML = `<p class="error">${esc(e.message)}</p>`; } }
  async function submitFeedback(event) { event.preventDefault(); try { const data = await get("/api/v1/feedback", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ feedback_type:document.querySelector("#feedbackType").value, rating:Number(document.querySelector("#rating").value), message:document.querySelector("#message").value, email:document.querySelector("#email").value || null }) }); toast(data.message || "Feedback sent."); event.target.reset(); } catch (e) { toast(e.message); } }
  function showError(error) { view().innerHTML = `<div class="card full"><p class="error">Could not connect to SETU: ${esc(error.message)}. Please start the backend and try again.</p></div>`; }
  if (loggedIn()) renderDashboard(); else renderLogin();
})();
